# Generated by Django 5.1.1 on 2024-10-27 20:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='last_heartbeat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
