version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: django_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - SQL_ENGINE=django.contrib.gis.db.backends.postgis
      - SQL_DATABASE=appdb
      - SQL_USER=appuser
      - SQL_PASSWORD=apppassword
      - SQL_HOST=db
      - SQL_PORT=5432
      - DEBUG=1
    env_file:
      - .env
    command: >
      sh -c "sleep 5 &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgis/postgis:15-3.3
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser"]
      interval: 5s
      timeout: 5s
      retries: 10


  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
    container_name: react_native_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8081:8081"
    command: npm start

volumes:
  pgdata:
