export const fonts = {
  primary: {
    black: 'Poppins-Black',
    blackItalic: 'Poppins-BlackItalic',
    bold: 'Poppins-Bold',
    boldItalic: 'Poppins-BoldItalic',
    extraBold: 'Poppins-ExtraBold',
    extraBoldItalic: 'Poppins-ExtraBoldItalic',
    extraLight: 'Poppins-ExtraLight',
    extraLightItalic: 'Poppins-ExtraLightItalic',
    italic: 'Poppins-Italic',
    lightItalic: 'Poppins-LightItalic',
    medium: 'Poppins-Medium',
    mediumItalic: 'Poppins-MediumItalic',
    regular: 'Poppins-Regular',
    semiBold: 'Poppins-SemiBold',
    semiBoldItalic: 'Poppins-SemiBoldItalic',
    thin: 'Poppins-Thin',
    thinItalic: 'Poppins-ThinItalic',
  },
  secondary: {
    boldOblique: 'Quicksand_Bold_Oblique',
    bold: 'Quicksand_Bold',
    light: 'Quicksand_Light',
    lightOblique: 'Quicksand_Light_Oblique',
    dash: 'Quicksand_Dash',
    book: 'Quicksand_Book',
    bookOlique: 'Quicksand_Bold_Oblique',
    regular: 'Quicksand_Regular',
  },
  tertiary: {
    black: 'Raleway-Black',
    bold: 'Raleway-Bold',
    extraBold: 'Raleway-ExtraBold',
    italic: 'Raleway-Italic',
    light: 'Raleway-Light',
    medium: 'Raleway-Medium',
    mediumItalic: 'Raleway-MediumItalic',
    regular: 'Raleway-Regular',
    semiBold: 'Raleway-SemiBold',
    thin: 'Raleway-Thin',
    thinItalic: 'Raleway-ThinItalic',
  },
};
