# Generated by Django 5.1.1 on 2024-09-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_price_per_meter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price_per_meter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
