# Generated by Django 5.1.1 on 2024-10-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_propertyclick_guest_id_propertyinquiry_guest_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='total_view_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
