# Generated by Django 4.2.16 on 2024-10-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_total_view_duration_property_view_count'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(check=models.Q(('property_age__gte', 0), ('property_age__lte', 99)), name='check_property_age_range'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(check=models.Q(('property_videos__len__lte', 3)), name='chk_property_videos'),
        ),
    ]
