# Generated by Django 5.1.1 on 2025-02-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_scrolllog_searchlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='current_step',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
