# Generated by Django 5.1.1 on 2025-02-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_property_current_step_property_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='total_view_duration',
        ),
        migrations.RemoveField(
            model_name='property',
            name='view_count',
        ),
        migrations.AddField(
            model_name='property',
            name='commission',
            field=models.DecimalField(blank=True, choices=[(0.5, '0.5%'), (1.0, '1.0%'), (1.5, '1.5%'), (2.0, '2.0%'), (2.5, '2.5%')], decimal_places=1, help_text='Commission percentage (from 0.5% to 2.5% in 0.5% increments)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_plan',
            field=models.FileField(blank=True, help_text='Upload the floor plan file or image', null=True, upload_to='floor_plans/'),
        ),
        migrations.AddField(
            model_name='property',
            name='main_image_index',
            field=models.IntegerField(default=0, help_text='Index of the main image/video to display first'),
        ),
        migrations.AddField(
            model_name='property',
            name='rent_duration',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], help_text='Rental period (e.g., Monthly, Quarterly, Semi-Annual, Annual)', max_length=20, null=True),
        ),
    ]
