# Generated by Django 5.1.1 on 2025-02-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_remove_property_total_view_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='total_view_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
