# Generated by Django 5.1.1 on 2024-09-23 11:07

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_type', models.CharField(choices=[('short_term_rent', 'Short Term Rent'), ('long_term_rent', 'Long Term Rent'), ('for_sale', 'For Sale'), ('land_rent', 'Land Rent'), ('land_sale', 'Land Sale')], max_length=50)),
                ('property_category', models.CharField(choices=[('House', 'House'), ('Shop', 'Shop'), ('Office', 'Office'), ('Apartment', 'Apartment'), ('Tower', 'Tower'), ('Chalet', 'Chalet'), ('Warehouse', 'Warehouse'), ('Workers Residence', 'Workers Residence'), ('Land', 'Land'), ('Farmland', 'Farmland')], max_length=50)),
                ('property_age', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_meter', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('listing_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('available', 'Available'), ('pending', 'Pending'), ('sold', 'Sold'), ('rented', 'Rented')], max_length=50, null=True)),
                ('contact_information', models.TextField(blank=True, null=True)),
                ('property_images', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('property_videos', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=3)),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_until', models.DateTimeField(blank=True, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('has_water', models.BooleanField(default=False)),
                ('has_electricity', models.BooleanField(default=False)),
                ('has_sewage', models.BooleanField(default=False)),
                ('direction', models.CharField(blank=True, choices=[('North', 'North'), ('South', 'South'), ('East', 'East'), ('West', 'West')], max_length=10, null=True)),
                ('floors', models.IntegerField(blank=True, null=True)),
                ('living_rooms', models.IntegerField(blank=True, null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('floor_number', models.IntegerField(blank=True, null=True)),
                ('number_of_streets', models.IntegerField(blank=True, null=True)),
                ('foot_traffic', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True)),
                ('proximity', models.CharField(blank=True, max_length=50, null=True)),
                ('parking_spaces', models.IntegerField(blank=True, null=True)),
                ('number_of_gates', models.IntegerField(blank=True, null=True)),
                ('loading_docks', models.IntegerField(blank=True, null=True)),
                ('storage_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number_of_units', models.IntegerField(blank=True, null=True)),
                ('property_features', models.JSONField(blank=True, null=True)),
                ('ad_id', models.IntegerField(blank=True, null=True)),
                ('ad_license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('unified_number_of_establishment', models.CharField(blank=True, max_length=100, null=True)),
                ('fal_license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('fal_registration_date', models.DateTimeField(blank=True, null=True)),
                ('advertiser_info', models.JSONField(blank=True, null=True)),
                ('similar_properties', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            # options={
            #     'constraints': [models.CheckConstraint(condition=models.Q(('property_age__gte', 0), ('property_age__lte', 99)), name='check_property_age_range'), models.CheckConstraint(condition=models.Q(('property_videos__len__lte', 3)), name='chk_property_videos')],
            # },
        ),
    ]
