# Generated by Django 5.1.1 on 2024-09-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price_per_meter',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
