# Generated by Django 5.1.1 on 2024-09-25 18:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_coordinates_alter_property_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ownership_type',
            field=models.CharField(choices=[('independent', 'Independent'), ('multipleOwners', 'Multiple Owners'), ('agency', 'Agency')], default='indenependent', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.DecimalField(decimal_places=2, help_text='Size in square meters', max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
