# Generated by Django 5.1.1 on 2024-11-05 21:57

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_property_check_property_age_range_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrollLog',
            fields=[
                ('scroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('guest_id', models.CharField(blank=True, max_length=255, null=True)),
                ('time_diff', models.IntegerField(help_text='Time spent scrolling in seconds')),
                ('scroll_date', models.DateTimeField(auto_now_add=True)),
                ('geo_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('search_id', models.AutoField(primary_key=True, serialize=False)),
                ('guest_id', models.CharField(blank=True, max_length=255, null=True)),
                ('search_query', models.CharField(max_length=255)),
                ('filters', models.JSONField(blank=True, null=True)),
                ('search_date', models.DateTimeField(auto_now_add=True)),
                ('geo_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
