export const fonts = {
  primary: {
    black: 'Poppins-Black',
    blackItalic: 'Poppins-BlackItalic',
    bold: 'Poppins-Bold',
    boldItalic: 'Poppins-BoldItalic',
    extraBold: 'Poppins-ExtraBold',
    extraBoldItalic: 'Poppins-ExtraBoldItalic',
    extraLight: 'Poppins-ExtraLight',
    extraLightItalic: 'Poppins-ExtraLightItalic',
    italic: 'Poppins-Italic',
    lightItalic: 'Poppins-LightItalic',
    medium: 'Poppins-Medium',
    mediumItalic: 'Poppins-MediumItalic',
    regular: 'Poppins-Regular',
    semiBold: 'Poppins-SemiBold',
    semiBoldItalic: 'Poppins-SemiBoldItalic',
    thin: 'Poppins-Thin',
    thinItalic: 'Poppins-ThinItalic',
    // Added Jost fonts
    jostBlack: 'Jost-Black',
    jostBlackItalic: 'Jost-BlackItalic',
    jostBold: 'Jost-Bold',
    jostBoldItalic: 'Jost-BoldItalic',
    jostExtraBold: 'Jost-ExtraBold',
    jostExtraBoldItalic: 'Jost-ExtraBoldItalic',
    jostExtraLight: 'Jost-ExtraLight',
    jostExtraLightItalic: 'Jost-ExtraLightItalic',
    jostItalic: 'Jost-Italic',
    jostLight: 'Jost-Light',
    jostLightItalic: 'Jost-LightItalic',
    jostMedium: 'Jost-Medium',
    jostMediumItalic: 'Jost-MediumItalic',
    jostRegular: 'Jost-Regular',
    jostSemiBold: 'Jost-SemiBold',
    jostSemiBoldItalic: 'Jost-SemiBoldItalic',
    jostThin: 'Jost-Thin',
    jostThinItalic: 'Jost-ThinItalic',
  },
  secondary: {
    boldOblique: 'Quicksand_Bold_Oblique',
    bold: 'Quicksand_Bold',
    light: 'Quicksand_Light',
    lightOblique: 'Quicksand_Light_Oblique',
    dash: 'Quicksand_Dash',
    book: 'Quicksand_Book',
    bookOblique: 'Quicksand_Book_Oblique',
    regular: 'Quicksand_Regular',
    // Added Jost fonts
    jostBoldOblique: 'Jost-BoldOblique',
    jostBook: 'Jost-Book',
    jostBookOblique: 'Jost-BookOblique',
  },
  tertiary: {
    black: 'Raleway-Black',
    bold: 'Raleway-Bold',
    extraBold: 'Raleway-ExtraBold',
    italic: 'Raleway-Italic',
    light: 'Raleway-Light',
    medium: 'Raleway-Medium',
    mediumItalic: 'Raleway-MediumItalic',
    regular: 'Raleway-Regular',
    semiBold: 'Raleway-SemiBold',
    thin: 'Raleway-Thin',
    thinItalic: 'Raleway-ThinItalic',
    // Added Jost fonts
    jostBlack: 'Jost-Black',
    jostBold: 'Jost-Bold',
    jostExtraBold: 'Jost-ExtraBold',
    jostItalic: 'Jost-Italic',
    jostLight: 'Jost-Light',
    jostMedium: 'Jost-Medium',
    jostMediumItalic: 'Jost-MediumItalic',
    jostRegular: 'Jost-Regular',
    jostSemiBold: 'Jost-SemiBold',
    jostThin: 'Jost-Thin',
    jostThinItalic: 'Jost-ThinItalic',
  },
};
